Repository EAWF/Bitcoin-Merchants-Toolbox, pull requests merged in 2020-08, with the labels that each got.

#32 Repo restructuring
  README.md
  Toolbox/README.md
  Toolbox/docs/README.md
  Toolbox/getBTC.conf
  Toolbox/getBTC.conf.md
  Toolbox/getBTC.java
  Toolbox/getBTC.js
  Toolbox/getBTC.php
  Toolbox/getBTC.rb
  Toolbox/getBTCAddress.md
  Toolbox/getBTCAddress/README.md
  Toolbox/getBTCBalance/README.md
  Toolbox/getBTCInvoice/README.md
  Toolbox/getBTCRate/README.md
  Toolbox/tests/README.md
  Toolbox/tests/tests.java
  Toolbox/tests/tests.js
  Toolbox/tests/tests.php
  Toolbox/tests/tests.py
  Toolbox/tests/tests.rb
  Toolbox/tests/vectors.json
  etc/ExPub-Data-Extraction.md
  etc/Private2PublicKey.md
  etc/Related-Information.md
  etc/Toolbox_snippet.md
  etc/getBTCBalance_snippet.md
  etc/getBTCInvoice_snippet.md
  etc/getBTCRate_snippet.md
Labels: documentation

#47 Bug Fix: #46 - Namespace Declaration Failure
  Toolbox/docs/php/classes/BTCTestVectors.html
  Toolbox/docs/php/classes/Bech32.html
  Toolbox/docs/php/classes/BitcoinECC.html
  Toolbox/docs/php/classes/ExtendedPublicKey.html
  Toolbox/docs/php/classes/HashUtil.html
  Toolbox/docs/php/classes/Logger.html
  Toolbox/docs/php/classes/Singleton.html
  Toolbox/docs/php/classes/TestLogger.html
  Toolbox/docs/php/files/getBTC.html
  Toolbox/docs/php/files/tests.tests.html
  Toolbox/docs/php/graphs/class.html
  Toolbox/docs/php/graphs/classes.svg
  Toolbox/docs/php/index.html
  Toolbox/docs/php/namespaces/BTC.Test.html
  Toolbox/docs/php/namespaces/BTC.html
  Toolbox/docs/php/namespaces/default.html
  Toolbox/docs/php/reports/deprecated.html
  Toolbox/docs/php/reports/errors.html
  Toolbox/docs/php/reports/markers.html
  Toolbox/getBTC.php
  Toolbox/tests/tests.php
Labels: bug

#57 Create getBTCRate Errors.md
  RFC/getBTCRate Errors.md
Labels: enhancement, question
